name: news_app_test
description: A simple app to get the lastest news from the internet across the world.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: 3.7.0

dependencies:
  bloc: ^8.1.0
  build_runner: ^2.3.3
  dio: ^4.0.6
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  pull_to_refresh: ^2.0.0
  webview_flutter: ^4.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
